<a href="https://colab.research.google.com/github/galua2001/colab/blob/main/nn2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
n=100
np.random.seed(1)

In [27]:
tx=(np.random.rand(n,2)*n).astype(np.int32)+1

In [28]:
print(tx)

[[ 42  73]
 [  1  31]
 [ 15  10]
 [ 19  35]
 [ 40  54]
 [ 42  69]
 [ 21  88]
 [  3  68]
 [ 42  56]
 [ 15  20]
 [ 81  97]
 [ 32  70]
 [ 88  90]
 [  9   4]
 [ 17  88]
 [ 10  43]
 [ 96  54]
 [ 70  32]
 [ 69  84]
 [  2  76]
 [ 99  75]
 [ 29  79]
 [ 11  45]
 [ 91  30]
 [ 29  14]
 [  2  68]
 [ 22  27]
 [ 50   6]
 [ 58  15]
 [ 59  70]
 [ 11  42]
 [ 70  42]
 [  5  54]
 [ 67  52]
 [ 95  59]
 [ 91  14]
 [ 14  81]
 [ 40  17]
 [ 93  35]
 [ 76  73]
 [ 89  63]
 [ 76  35]
 [ 27  90]
 [ 43  97]
 [ 67  63]
 [ 12  95]
 [ 45  58]
 [ 41  24]
 [ 91  58]
 [  1  62]
 [ 33  53]
 [ 89  36]
 [ 91  63]
 [  2  93]
 [ 70 100]
 [ 18  14]
 [ 94  70]
 [  7  76]
 [ 76  93]
 [ 72  13]
 [  2   3]
 [  3  25]
 [ 87  54]
 [ 56  85]
 [ 13  28]
 [ 59  97]
 [ 57   2]
 [ 81  24]
 [ 81  39]
 [ 87  75]
 [ 56  14]
 [  6  13]
 [  5  11]
 [ 23  72]
 [ 56   2]
 [  8  97]
 [ 57  21]
 [ 26  75]
 [ 20  59]
 [ 98  85]
 [ 24  50]
 [ 62  83]
 [ 16   2]
 [  8  49]
 [ 61  57]
 [ 32  99]
 [ 58  39]
 [ 56  75]
 [ 67  27]
 [  7  38]
 [ 63  22]

In [29]:
 ty = (tx.min(axis=1) / tx.max(axis=1) <= 0.2).astype(np.int32)[np.newaxis].T

In [30]:
 print(ty)

[[0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]


In [31]:
mu=tx.mean(axis=0)
sigma=tx.std(axis=0)

In [32]:
def st(x):
  return(x-mu)/sigma

In [33]:
tx=st(tx)

In [34]:
w1=np.random.rand(2,2)

In [35]:
print(w1)

[[0.95017612 0.55665319]
 [0.91560635 0.64156621]]


In [36]:
w2=np.random.rand(2,2)
w3=np.random.rand(1,2)
b1=np.random.rand(2)
b2=np.random.rand(2)
b3=np.random.rand(1)

In [37]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [38]:
def forward(x0):
  z1=np.dot(x0, w1.T)+b1
  a1=sigmoid(z1)
  z2=np.dot(a1,w2.T)+b2
  a2=sigmoid(z2)
  z3=np.dot(a2, w3.T)+b3
  a3=sigmoid(z3)
  return a1,a2,z3,z1,z2,a3


In [39]:
def dsigmoid(x):
  return (1-sigmoid(x))*sigmoid(x)

In [40]:
def delta_output(z,y):
  return (sigmoid(z)-y)*dsigmoid(z)

In [41]:
def delta_hidden(z,d,w):
  return dsigmoid(z)*np.dot(d,w)

In [42]:
def backward(y,z3,z2,z1):
  d3=delta_output(z3,y)
  d2=delta_hidden(z2,d3,w3)
  d1=delta_hidden(z1,d2,w2)
  return d1,d2,d3

In [43]:
eta=0.001

In [44]:
def dweight(d,a):
  return eta*np.dot(d.T,a)

In [45]:
def dbias(d):
  return d.sum(axis=0)

In [46]:
def update_parameters(d3,x2,d2,x1,d1,x0):
  global w1,w2,w3,b1,b2,b3
  w3=w3-eta*dweight(d3,x2)
  w2=w2-eta*dweight(d2,x1)
  w1=w1-eta*dweight(d1,x0)
  b3=b3-eta*dbias(d3)
  b2=b2-eta*dbias(d2)
  b1=b1-eta*dbias(d1)


In [47]:
def train(x,y):
  a1,a2,a3,z1,z2,z3=forward(x)
  d1,d2,d3=backward(y,z3,z2,z1)
  update_parameters(d3,a2,d2,a1,d1,x)

In [48]:
EPOCH = 30000

In [49]:
def predict(X):
    return forward(X)[-1]


In [50]:
def E(Y, X):
    return 0.5 * ((Y - predict(X)) ** 2).sum()

In [51]:
import math

In [52]:
BATCH = 100

for epoch in range(1, EPOCH + 1):
    # ミニバッチ学習用にランダムなインデックスを取得
    p = np.random.permutation(len(tx))

    # ミニバッチの数分だけデータを取り出して学習
    for i in range(math.ceil(len(tx) / BATCH)):
        indice = p[i*BATCH:(i+1)*BATCH]
        X0 = tx[indice]
        # Convert indice to a list to use it as index for the list ty
        Y  =  ty[indice]

        train(X0, Y)

      # ログを残す
    if epoch % 100 == 0:
      log = '誤差 = {:8.4f} ({:5d}エポック目)'
      print(log.format(E(ty, tx), epoch))

誤差 =  15.6041 (  100エポック目)
誤差 =   9.9148 (  200エポック目)
誤差 =   9.2519 (  300エポック目)
誤差 =  10.0315 (  400エポック目)
誤差 =  10.7097 (  500エポック目)
誤差 =  11.1036 (  600エポック目)
誤差 =  11.3064 (  700エポック目)
誤差 =  11.4063 (  800エポック目)
誤差 =  11.4547 (  900エポック目)
誤差 =  11.4781 ( 1000エポック目)
誤差 =  11.4893 ( 1100エポック目)
誤差 =  11.4948 ( 1200エポック目)
誤差 =  11.4974 ( 1300エポック目)
誤差 =  11.4987 ( 1400エポック目)
誤差 =  11.4994 ( 1500エポック目)
誤差 =  11.4997 ( 1600エポック目)
誤差 =  11.4998 ( 1700エポック目)
誤差 =  11.4999 ( 1800エポック目)
誤差 =  11.5000 ( 1900エポック目)
誤差 =  11.5000 ( 2000エポック目)
誤差 =  11.5000 ( 2100エポック目)
誤差 =  11.5000 ( 2200エポック目)
誤差 =  11.5000 ( 2300エポック目)
誤差 =  11.5000 ( 2400エポック目)
誤差 =  11.5000 ( 2500エポック目)
誤差 =  11.5000 ( 2600エポック目)
誤差 =  11.5000 ( 2700エポック目)
誤差 =  11.5000 ( 2800エポック目)
誤差 =  11.5000 ( 2900エポック目)
誤差 =  11.5000 ( 3000エポック目)
誤差 =  11.5000 ( 3100エポック目)
誤差 =  11.5000 ( 3200エポック目)
誤差 =  11.5000 ( 3300エポック目)
誤差 =  11.5000 ( 3400エポック目)
誤差 =  11.5000 ( 3500エポック目)
誤差 =  11.5000 ( 3600エポック目)
誤差 =  11.5000 ( 3700エポック目)
誤

In [54]:
def classify(X):
    return (predict(X) > 0.8).astype(np.int32)

In [56]:
TEST_N = 1000
testX = (np.random.rand(TEST_N, 2) * 1000).astype(np.int32) + 1
testY = (testX.min(axis=1) / testX.max(axis=1) <= 0.2).astype(np.int32)[np.newaxis].T

In [58]:
accuracy = (classify(st(testX)) == testY).sum() / TEST_N
print('精度: {}%'.format(accuracy * 100))


精度: 81.10000000000001%
